### ISSUE TITLE
RROR:  While executing gem ... (Gem::RemoteFetcher::FetchError)     SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed 

### ISSUE THREAD

**Issue by sarmadm** [nsrr/nsrr-gem#15] opened 2016-10-25 08:44 UTC
Hi when I type this command in windows cmd :  gem update --system 2.4.8 --no-document

this error is dispalyed , how can I fix it ?

C:\Users\sarmad>gem update --system 2.4.8 --no-document
ERROR:  While executing gem ... (Gem::RemoteFetcher::FetchError)
    SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed (https://api.rubygems.org/specs.4.8.gz)

**Comment by remomueller** [comment] 2016-10-25 14:09
This looks like an issue with the SSL certificates installed on your system that are used by Ruby. Can you provide the output for `gem install nsrr --no-document` and `nsrr v`?

Thanks!

**Comment by remomueller** [comment] 2016-10-25 14:18
Since you're on Windows, you will also need to have installed DevKit when installing Ruby as per instructions here: https://github.com/remomueller/documentation/blob/master/windows/130-ruby.md

If any particular steps are getting you errors, let me know where you run into an issue. (You may not need to downgrade the gem system to 2.4.8).

**Comment by remomueller** [comment] 2016-12-13 15:02
Hi @sarmadm, I'm going to close this issue as the cause is not directly related to the NSRR gem. If you can provide further details, I can revisit and reopen the issue in the future if necessary.

I updated the [Windows documentation for installing Ruby](https://github.com/remomueller/documentation/blob/master/windows/130-ruby.md) and the NSRR gem as well, and did not run into the issue you described.

If you have any other questions, please let me know, thanks!

**Closed by remomueller** 2016-12-13 15:02 UTC
